-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 13:56:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baza_pp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baza_pp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baza_pp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `baza_pp` ;

-- -----------------------------------------------------
-- Table `baza_pp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza_pp`.`user` (
  `UserName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserName`),
  UNIQUE INDEX `UserName` (`UserName` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baza_pp`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza_pp`.`account` (
  `AccountNumber` INT NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(10,2) NOT NULL,
  `currencyCode` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AccountNumber`),
  UNIQUE INDEX `AccountNumber` (`AccountNumber` ASC) VISIBLE,
  INDEX `UserName` (`UserName` ASC) VISIBLE,
  CONSTRAINT `account_ibfk_1`
    FOREIGN KEY (`UserName`)
    REFERENCES `baza_pp`.`user` (`UserName`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baza_pp`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza_pp`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baza_pp`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza_pp`.`transfer` (
  `idTransfer` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `currencyCode` VARCHAR(45) NOT NULL,
  `fromAccountNumber` INT NOT NULL,
  `toAccountNumber` INT NOT NULL,
  PRIMARY KEY (`idTransfer`),
  UNIQUE INDEX `idTransfer` (`idTransfer` ASC) VISIBLE,
  INDEX `fromAccountNumber` (`fromAccountNumber` ASC) VISIBLE,
  INDEX `toAccountNumber` (`toAccountNumber` ASC) VISIBLE,
  CONSTRAINT `transfer_ibfk_1`
    FOREIGN KEY (`fromAccountNumber`)
    REFERENCES `baza_pp`.`account` (`AccountNumber`),
  CONSTRAINT `transfer_ibfk_2`
    FOREIGN KEY (`toAccountNumber`)
    REFERENCES `baza_pp`.`account` (`AccountNumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
